### PR TITLE
add package.json and regenerate package-lock.json

### PR DESCRIPTION
**Pull request by fdiblen**
adds package.json

### CODE REVIEW

**Comment by fdiblen** [comment]
@pedrohserrano @Alialsaeedi1 can you please review the changes in this PR? If everything looks good, I will merge it.

**Comment by Alialsaeedi1** [comment]
I tried using the extension with the package updates but the evaluation is not working

**Review by Alialsaeedi1 — APPROVED** [review]
Hi Faruk, I was trying to find why this commit wouldn't work for me and I found out that it has to do with the xmlhttprequest package in my computer. I took a look on the automation of browserify and I think it's a great addition as developers now don't have to deal with the creation of bundle.js. Good Job!

**Comment by fdiblen** [comment]
Thank you for the review @Alialsaeedi1 !

**Pull request merged**
