### PR TITLE
removed the license badge from README.md

### LINKED ISSUE #36: Remove the license badge
The license badge is not really needed in the README.md. Shall we remove it?

### PR DESCRIPTION
**Pull request by fdiblen**
Fixes #36

### CODE REVIEW

**Review by Alialsaeedi1 — COMMENTED** [review]
I think license should always be included in the README.md file, how about replacing it with another license?

**Review by pedrohserrano — CHANGES_REQUESTED** [review]
I think we should not remove the license badge

**Review by Alialsaeedi1 — APPROVED** [review]
Indeed license should be removed. Great job!

**Review by pedrohserrano — APPROVED** [review]
The team has realized that the license is already in the repository metadata attributes. So the badge is redundant

**Comment by fdiblen** [comment]
Thank you for reviewing @pedrohserrano @Alialsaeedi1!

**Pull request merged**
